# Workflow name
name: "Accessibility Audit"

# Event for the workflow
on:
  pull_request:
    branches:
      - master

# List of jobs
jobs:
  test:
    # Operating System
    runs-on: ubuntu-latest
    # Job steps
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: yarn
      - name: Start Storybook
        run: yarn storybook &
      - name: Storybook tests
        run: |
          yarn test-storybook
      - name: Stop Storybook
        run: kill $(lsof -t -i:6006)
